from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncEngine
from sqlalchemy import inspect as sa_inspect

async def up(engine: AsyncEngine):
    """
    Version: v1.1.0 (from v1.0.4)
    Add graph-schema columns (node_uuid on memories, edge_id on paths).
    Also explicitly create new tables 'nodes' and 'edges'.
    """
    def check_mem_col(connection):
        inspector = sa_inspect(connection)
        return "node_uuid" in [col["name"] for col in inspector.get_columns("memories")]
        
    def check_path_col(connection):
        inspector = sa_inspect(connection)
        return "edge_id" in [col["name"] for col in inspector.get_columns("paths")]

    async with engine.begin() as conn:
        is_postgres = "postgresql" in str(engine.url)
        edge_id_column = (
            "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
            if is_postgres
            else "id INTEGER PRIMARY KEY AUTOINCREMENT"
        )

        await conn.execute(text(
            """
            CREATE TABLE IF NOT EXISTS nodes (
                uuid VARCHAR(36) PRIMARY KEY,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
            """
        ))
        
        await conn.execute(text(
            f"""
            CREATE TABLE IF NOT EXISTS edges (
                {edge_id_column},
                parent_uuid VARCHAR(36) NOT NULL REFERENCES nodes(uuid),
                child_uuid VARCHAR(36) NOT NULL REFERENCES nodes(uuid),
                name VARCHAR(256) NOT NULL,
                priority INTEGER DEFAULT 0,
                disclosure TEXT,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT uq_edge_parent_child UNIQUE(parent_uuid, child_uuid)
            )
            """
        ))

        has_mem_col = await conn.run_sync(check_mem_col)
        if not has_mem_col:
            await conn.execute(text("ALTER TABLE memories ADD COLUMN node_uuid VARCHAR(36) REFERENCES nodes(uuid)"))
            
        has_path_col = await conn.run_sync(check_path_col)
        if not has_path_col:
            await conn.execute(text("ALTER TABLE paths ADD COLUMN edge_id INTEGER REFERENCES edges(id)"))
