import logging
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncEngine

logger = logging.getLogger(__name__)


async def up(engine: AsyncEngine):
    """
    Version: v1.2.0
    Add glossary_keywords table for the glossary (豆辞典) feature.

    Each row binds a keyword string to a node UUID.
    UNIQUE(keyword, node_uuid) prevents duplicate bindings.
    """
    async with engine.begin() as conn:
        is_postgres = "postgresql" in str(engine.url)
        id_column = (
            "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
            if is_postgres
            else "id INTEGER PRIMARY KEY AUTOINCREMENT"
        )

        await conn.execute(
            text(
                f"""
                CREATE TABLE IF NOT EXISTS glossary_keywords (
                    {id_column},
                    keyword TEXT NOT NULL,
                    node_uuid TEXT NOT NULL REFERENCES nodes(uuid) ON DELETE CASCADE,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT uq_glossary_keyword_node UNIQUE(keyword, node_uuid)
                )
                """
            )
        )

        await conn.execute(
            text(
                "CREATE INDEX IF NOT EXISTS idx_glossary_keyword "
                "ON glossary_keywords(keyword)"
            )
        )

        logger.info(
            "Migration 008: created glossary_keywords table with index"
        )
